const COUNTRY_MAP: Record<string, string> = {
    AAPL: 'САЩ',
    AMD: 'САЩ',
    AMZN: 'САЩ',
    AVGO: 'САЩ',
    BABA: 'Хонконг',
    BRK: 'САЩ',
    DAL: 'САЩ',
    ESTC: 'САЩ',
    ET: 'САЩ',
    GOOG: 'САЩ',
    GTLB: 'САЩ',
    META: 'САЩ',
    MDB: 'САЩ',
    MSFT: 'САЩ',
    NFLX: 'САЩ',
    NVDA: 'САЩ',
    PLTR: 'САЩ',
    PRGS: 'САЩ',
    PYPL: 'САЩ',
    QCOM: 'САЩ',
    ROKU: 'САЩ',
    SBUX: 'САЩ',
    VCLT: 'САЩ',
    XOM: 'САЩ',
    CSPX: 'Ирландия',
    SXR8: 'Ирландия',
    GLDV: 'Ирландия',
    ZPRG: 'Ирландия',
    VHYL: 'Ирландия',
    JGPI: 'Ирландия',
    VWCE: 'Ирландия',
    ISPA: 'Германия',
    ISPAd: 'Германия',
    LHA: 'Германия',
    SAP: 'Германия',
    TMV: 'Германия',
    TKWY: 'Германия',
    ASML: 'Нидерландия (Холандия)',
    RIO: 'Великобритания',
    '1810': 'Хонконг',
};

export function resolveCountry(symbol: string): string {
    return COUNTRY_MAP[symbol] ?? '';
}
